config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get '/payment' => 'pages#payment'
  # get '/about' => 'pages#about'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :listings, except: [:destroy] do
    resources :bookings, only: [:create, :update]
  end
  resources :bookings, only: [:index, :show, :destroy] do
    resources :chatrooms, only: [:show, :create] # nested chatrooms inside bookings so a booking has a chat
  end
  resources :chatrooms, only: [:show] do
    resources :messages , only: :create
  end
  resources :reviews
  delete "bookings/:id", to: "bookings#destroy", as: :delete_booking
  delete "listings/:id", to: "listings#destroy", as: :delete
  get "dashboard", to: "users#dashboard", as: :dashboard # custom route - we have to create a users controller as well

end

app/models/listing.rb
require 'json'
require 'open-uri'

class Listing < ApplicationRecord
  has_many :bookings, dependent: :destroy
  belongs_to :user

  validates :currency_amount, presence: true
  validates :currency_amount, numericality: { only_integer: true, greater_than: 0 }
  validates :currency, presence: true
  validates :location, presence: true

  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?

  include PgSearch::Model
  pg_search_scope :search_by_currency,
    against: [ :currency ],
    using: {
      tsearch: { prefix: true } # <-- now `superman batm` will return something!
    }
  pg_search_scope :search_by_location,
  against: [ :location ],
  using: {
    tsearch: { prefix: true } # <-- now `superman batm` will return something!
  }

  def self.get_currencies
    url = 'https://gist.githubusercontent.com/Fluidbyte/2973986/raw/8bb35718d0c90fdacb388961c98b8d56abc392c9/Common-Currency.json'

    currencies_serialized = open(url).read
    currencies = JSON.parse(currencies_serialized)

    parsed_currencies = currencies.to_a.map do |currency|
      currency = "#{currency[1]["code"]} - #{currency[1]["name"]}"
    end
  end
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show, :new]

  def index
    if params[:where].present?
      if params[:distance] == ""
        @listings = Listing.near(params[:where], 0)
      else
        @listings = Listing.near(params[:where], params[:distance])
      end
      if params[:query].present?
        @listings = @listings.where("currency ILIKE? ", "%#{params[:query]}%")
      end
    else
      # @listings = Listing.take(8)
      @listings = Listing.all.sort_by { |listing| listing.created_at }.reverse! # having it sort by most recently made
    end
    @markers = @listings.map do |listing|
      {
        lat: listing.latitude,
        lng: listing.longitude,
        infoWindow: render_to_string(partial: "info_window", locals: { listing: listing }),
        image_url: helpers.asset_url('yen.png')
      }
    end
    @pagy_a, @loaded_listings = pagy_array(@listings)
  
    respond_to do |format|
      format.html
      format.json {
        render json: { entries: render_to_string(partial: "listings", formats: [:html]), pagination: view_context.pagy_nav(@pagy_a) }
      }
    end
  end
  
  def show
    @listing = Listing.find(params[:id])
    @user = @listing.user
    @reviews = @user.received_reviews
  end

  def new
    @currencies = Listing.get_currencies
    # page where the form is displayed
    @listing = Listing.new
  end

  def create
    @listing = Listing.new(listing_params)
    @listing.user = current_user
    @listing.transaction_completed = false
    if @listing.save
      redirect_to dashboard_path
    else
      flash.alert = "Please check your form for any errors and try again."
      render :new
    end
  end

  def edit
    @listing = Listing.find(params[:id])
  end

  def update
    @listing = Listing.find(params[:id])
    if @listing.update(listing_params)
      redirect_to listing_path(@listing)
    else
      render :edit
    end
  end

  def destroy
    @listing = Listing.find(params[:id])
    @listing.destroy

    redirect_to dashboard_path
  end

  private

  def listing_params
    params.require(:listing).permit(:currency_amount, :currency, :location, :message)
  end
end

app/views/listings/_info_window.html.erb
<div class="info-window">
	<p><%= listing.currency_amount %><%= listing.currency %></p>
	<p><%= listing.user.first_name %> <%= listing.user.last_name %></p>
	<%= listing.user.email %>
	<br>
	<br>
	<%=link_to "book me", listing_bookings_path(listing), method: :post, class: "btn red" %>
</div>

app/views/listings/_listings.html.erb
            <% @loaded_listings.each do |listing|%>
                <% if current_user != listing.user %>
                    <div class="card m-2 p-4 showing">
                        <div class="top-listing-card d-flex">
                            <div class="card-top-left">
                                <p class="big-font"><strong><%= listing.location %></strong>
                                    <%# time_yest = Time.now - (24*60*60) %>
                                    <%# if listing.created_at > time_yest %>
                                    <% time_recent = Time.now - (60*60) %>
                                    <% if listing.created_at > time_recent %>
                                        <i class="just-added">Just added</i>
                                    <% end %>
                                </p>
                                <%= listing.user.email %>
                            </div>
                            <div class="card-top-right big-font">
                                <%= listing.currency[0,3] %>
                                <%= listing.currency_amount %>
                            </div>                
                        </div>
                        <hr>
                        <div class="card-bottom row px-3">
                            <p><%= listing.message %></p>
                            <%=link_to "book me", listing_bookings_path(listing), method: :post, class: "btn red" %>
                        </div>
                    </div>
                <% end %>
            <% end %>

app/views/listings/destroy.html.erb
<h1>Listings#destroy</h1>
<p>Find me in app/views/listings/destroy.html.erb</p>

app/views/listings/edit.html.erb
<div class="container">
	<h1>edit</h1>
	<p>Find me in app/views/listings/edit.html.erb</p>

	<%= simple_form_for(@listing) do |f| %>
	  <%= f.input :currency_amount, placeholder: @listing.currency_amount %>
	  <%= f.input :currency, placeholder: @listing.currency %>
	  <%= f.input :transaction_completed, placeholder: @listing.transaction_completed %>
	  <%= f.input :location, placeholder: @listing.location %>
	  <%= f.input :message, placeholder: @listing.message %>
	  <%= f.submit %>
	<% end %>
</div>

app/views/listings/index.html.erb
<div class="bg-dark min-height">
  <div class="container">
    <div class="row pt-3">
      <div class="col-6">
        <div class="pl-1">
          <%= form_tag listings_path, method: :get, class: "form-inline" do %>
            <%= text_field_tag :query,
            params[:query],
            class: "form-control",
            placeholder: "Which currency?" %>

            <%= text_field_tag :where,
            params[:where],
            class: "form-control",
            placeholder: "Where?" %>
            <%= number_field_tag :distance,
            params[:distance],
            class: "form-control",
            placeholder: "within how many km?"
            %>

            <%= submit_tag "Search", class: "btn red" %>
          <% end %>
        </div>
        <div data-controller="infinite-scroll" data-action="scroll@window->infinite-scroll#scroll">
          <div class="cards-index pt-3" data-infinite-scroll-target="entries">
            <%= render "listings" %>
          </div>
        
          <div data-infinite-scroll-target="pagination">
            <%== pagy_nav @pagy_a %>
          </div>
        </div>
      </div>
          <div class="col-6">
              <div id="map"
                style="height: 550px; position: sticky; top: 15"
                data-markers="<%= @markers.to_json %>"
                data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
              </div>
          </div>
    </div>
  </div>
</div>

app/views/listings/new.html.erb
<div class="bg-dark min-height">
  <div class="container">
    <div class="d-flex listing-container">
      <div class="payment">
        <%= image_tag "payment-processed.png", alt: "payment processed" %>
      </div>
      <div class="form-card">
        <h2><b>Exchange Your Cash</b></h2>
        <%= simple_form_for(@listing) do |f| %>
          <%= f.input :currency_amount, input_html: {class: 'currency-amount'} %>
          <%= f.input :currency, collection: @currencies, input_html: {class: 'dropdown-currency'} %>
          <div class="exchanged-currency"></div>
          <%= f.input :location %>
          <%= f.input :message %>
          <%= f.submit 'Create listing', class: 'blue-gradient-button' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/listings/show.html.erb
<% content_for :meta_title, "Book your #{@listing.currency} on #{DEFAULT_META["meta_product_name"]}" %>
<% content_for :meta_description, "Find exchanges for #{@listing.currency} and so much more on Revonew" %>

<div class='container'>
  <div class="listing-card-title"><p> Where ? <br> <%= @listing.location %></p><div class="listing-card-title-money"><p><p> What ? => <%= @listing.currency %> <%= @listing.currency_amount %></p></div></div>
  <p><%= @listing.user.first_name  %> <%= @listing.user.last_name %></p>
  <p>Important message : <%= @listing.message %></p>
  <div>
	<% if @listing.user == current_user %>
		<%= link_to "edit", edit_listing_path(@listing)  %>
		<% else%>
		  <%= link_to "book me", listing_bookings_path(@listing), method: :post %>
	<% end %>
  </div>
</div>