config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get '/payment' => 'pages#payment'
  # get '/about' => 'pages#about'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :listings, except: [:destroy] do
    resources :bookings, only: [:create, :update]
  end
  resources :bookings, only: [:index, :show, :destroy] do
    resources :chatrooms, only: [:show, :create] # nested chatrooms inside bookings so a booking has a chat
  end
  resources :chatrooms, only: [:show] do
    resources :messages , only: :create
  end
  resources :reviews
  delete "bookings/:id", to: "bookings#destroy", as: :delete_booking
  delete "listings/:id", to: "listings#destroy", as: :delete
  get "dashboard", to: "users#dashboard", as: :dashboard # custom route - we have to create a users controller as well

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :listings
  has_many :bookings
  has_many :requested_bookings, through: :listings, source: :bookings
  has_many :made_reviews, class_name: 'Review', foreign_key: 'reviewer_id'
  has_many :received_reviews, class_name: 'Review', foreign_key: 'reviewee_id'
  validates :first_name, presence: true
  validates :last_name, presence: true
  has_one_attached :photo

  def running_total
    @sum = 0
    self.requested_bookings.each do |booking|
      @sum += booking.listing.currency_amount.to_i
    end
    @sum
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def dashboard
    @listings = current_user.listings
    @bookings = current_user.bookings
    @my_bookings = current_user.requested_bookings
    if params[:paid].present?
      @paidalert = true
    end
  end
end

app/views/users/dashboard.html.erb
 <div class="dark-bg">
  <div class="container">
    <div class="d-flex home-container">

      <div class="user-info">
        <h4 class="user-greeting">Hello, <%= @current_user.first_name %>!</h4>
        <% if current_user.photo.attached? %>
          <%= cl_image_tag current_user.photo.key, alt: "temp", class: 'avatar-dash', gravity: :face, crop: :thumb  %>
        <% else %>
          <%= image_tag 'logo.png', alt: "temp", class: 'avatar-dash' %>
        <% end %>
        <p class="running-total">
          <% if current_user.requested_bookings.empty?  %>
            You've exchanged <strong>nothing yet</strong>, make your first exchange!
          <% else %>
            So far, you've exchanged:
            <span class="running-total-amount"><strong>€<%= @current_user.running_total %></strong></span>
          <% end %>
        </p>
      </div>
      <div class="user-content-container">
        <div class="nav" id="nav-tab" role="tablist">
          <ul class="nav nav-tabs" id="myTab" role="tablist">
            <li class="nav-item">
              <a class="nav-link active hvr-underline-from-left" id="home-tab" data-toggle="tab" href="#home" role="tab" aria-controls="home" aria-selected="true">My listings</a>
            </li>
            <li class="nav-item">
              <a class="nav-link hvr-underline-from-left" id="profile-tab" data-toggle="tab" href="#profile" role="tab" aria-controls="profile" aria-selected="false">My bookings</a>
            </li>
            <li class="nav-item">
              <a class="nav-link hvr-underline-from-left" id="contact-tab" data-toggle="tab" href="#contact" role="tab" aria-controls="contact" aria-selected="false">My requests <span class="request-number">(<%= @my_bookings.where(booking_status: false).count %>)</span></a>
            </li>
          </ul>
        </div>

        <div class="tab-content" id="myTabContent">
          <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
            <br>
            <% if @listings.empty? %>
              <div class="row justify-content-center no-listings">
                <h4>Doesn't look like you have any listings at the moment!</h4>
                <div class="button-for-listing">
                  <%= link_to 'Make a new listing', new_listing_path, class: " blue-gradient-button" %>
                </div>
              </div>
            <% end %>
            <% @listings.each do |listing| %>
              <div class="tab-card-styling">
                <div class="tab-card">
                  <div class="tab-card-heading">
                    <div class="tab-heading-left">
                      <h5 class="tab-card-location"><%= listing.location.upcase %></h5>
                      <p><i>Created on </i><%= listing.created_at.day %>/<%= listing.created_at.month %>/<%= listing.created_at.year %></p>
                    </div>
                    <div class="tab-card-currency">
                      <h5><%= listing.currency.upcase %></h5>
                      <h5 class="listing-currency-amount"><b><%= listing.currency_amount %></b></h5>
                    </div>
                  </div>
                  <hr>
                  <div class="tab-card-lower-half">
                    <div class="tab-card-message">
                      <h5><%= listing.message.capitalize %></h5>
                    </div>
                    <div class="modify-links">
                      <%= link_to 'EDIT', edit_listing_path(listing), class: "button-edit"%>
                      <%= link_to 'DELETE',  delete_path(listing), method: :delete, class: "button-delete" %>
                    </div>
                  </div>
                </div>
              </div>
            <% end %>
          </div>

          <div class="tab-pane fade" id="profile" role="tabpanel" aria-labelledby="profile-tab">
            <br>
            <% if @bookings.empty? %>
              <h4>Doesn't look like you have any bookings at the moment!</h4>
            <% end %>
            <% @bookings.each do |booking| %>
              <div class="tab-card-styling">
                <div class="tab-card">
                  <div class="tab-card-heading">
                    <div class="booking-message">
                      <h4>You're exchanging with <b><%= booking.listing.user.first_name %> <%= booking.listing.user.last_name %> - <%= booking.listing.user.email %></b></h4>
                      <p>in <strong><%= booking.listing.location %></strong></p>
                    </div>
                    <div class="tab-card-currency">
                      <h5><%= booking.listing.currency.upcase %></h5>
                      <h5 class="listing-currency-amount"><b><%= booking.listing.currency_amount %></b></h5>
                    </div>
                  </div>
                  <hr>
                  <div class="tab-card-lower-half">
                    <div class="tab-card-message">
                      <% if booking.booking_status == true %>
                        <h5>Booking confirmed</h5>
                        <% if booking.listing.transaction_completed == false %>
                          <%= link_to 'FINALIZE', listing_booking_path([booking.listing], [booking]), method: :patch, class: "button-accept" %>
                        <% else %>
                          <h4>TRANSACTION COMPLETED</h4>
                        <% end %>
                      <% else %>
                        <h6>Booking not confirmed yet</h6>
                      <% end %>
                    </div>
                    <div class="modify-links">
                      <%= link_to 'MESSAGE', booking_chatrooms_path(booking), method: :post, class: "button-edit"%>
                      <%= link_to 'CANCEL',  delete_booking_path(booking), method: :delete, class: "button-delete" %>
                    </div>
                  </div>
                </div>
              </div>
            <% end %>
          </div>

          <div class="tab-pane fade" id="contact" role="tabpanel" aria-labelledby="contact-tab">
            <br>
            <% if @my_bookings.empty? %>
              <h5>Doesn't look like you have any requests at the moment!</h5>
            <% end %>
            <% @my_bookings.each do |booking| %>
              <div class="tab-card-styling">
                <div class="tab-card">
                  <div class="tab-card-heading">
                    <div>
                      <h5>Request from <b><%= booking.user.first_name %> <%= booking.user.last_name %> - <%= booking.user.email %></b> for:</h5>
                    </div>
                    <div class="tab-card-currency-request">
                      <h5>Currency: <b><%= booking.listing.currency.upcase %></b></h5>
                      <h5>Amount: <b><%= booking.listing.currency_amount %></b></h5>
                    </div>
                  </div>
                  <hr>
                  <div class="tab-card-request-buttons">
                    <div class="booking-created-date">
                      <p><i>Request made on <%= booking.created_at.day %>/<%= booking.created_at.month %>/<%= booking.created_at.year %></i></p>
                    </div>
                    <div class="tab-card-message">
                      <% if booking.booking_status == false %>
                        <%= link_to "MESSAGE", booking_chatrooms_path(booking), method: :post, class: "button-edit" %>
                        <%= link_to 'ACCEPT', listing_booking_path([booking.listing], [booking]), method: :patch,class: "button-accept" %>
                        <%= link_to 'REFUSE', delete_booking_path(booking), method: :delete, class: "button-delete" %>
                      <% else %>
                        <%= link_to 'MESSAGE', booking_chatrooms_path(booking), method: :post, class: "button-edit"%>
                        <%= link_to 'CANCEL',  delete_booking_path(booking), method: :delete, class: "button-delete" %>
                      <% end %>
                    </div>
                  </div>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>


<% if @paidalert %>
  <div id="payalert"></div>
<% end %>

<!-- ([booking.listing], [booking]), method: :patch,  -->