config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get '/payment' => 'pages#payment'
  # get '/about' => 'pages#about'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :listings, except: [:destroy] do
    resources :bookings, only: [:create, :update]
  end
  resources :bookings, only: [:index, :show, :destroy] do
    resources :chatrooms, only: [:show, :create] # nested chatrooms inside bookings so a booking has a chat
  end
  resources :chatrooms, only: [:show] do
    resources :messages , only: :create
  end
  resources :reviews
  delete "bookings/:id", to: "bookings#destroy", as: :delete_booking
  delete "listings/:id", to: "listings#destroy", as: :delete
  get "dashboard", to: "users#dashboard", as: :dashboard # custom route - we have to create a users controller as well

end

app/views/pages/about.html.erb
<div class="dark-bg">
  <div class="about-carousel">
    <div class="carousel-card active">
      <div class="about-container">
        <h1>About</h1>
        <p>We worked hard.</p>
      </div>
      <div class="team-arrow">
        <button class="carousel-control-team">
          Meet the team
        </button>
      </div>
    </div>
    <div class="carousel-card">
      <div class="about-arrow">
        <button class="carousel-control-about">
          About
        </button>
      </div>
      <div class="team-container">
        <div class="team-desc">
          <h1>The Team</h1>
          <div class="about-row">
            <div class="about-card">
              <%= image_tag "logo.png", alt: "Stanley", class: 'avatar-bordered team' %>
              <div class="name">
                <h4>Stanley</h4>
              </div>
            </div>
            <div class="about-card">
              <%= image_tag "logo.png", alt: "alttext", class: 'avatar-bordered team' %>
              <div class="name">
                <h4>Maxime</h4>
              </div>
            </div>
            <div class="about-card">
              <%= image_tag "logo.png", alt: "alttext", class: 'avatar-bordered team' %>
              <div class="name">
                <h4>Danielle</h4>
              </div>
            </div>
            <div class="about-card">
              <%= image_tag "logo.png", alt: "alttext", class: 'avatar-bordered team' %>
              <div class="name">
                <h4>Hamza</h4>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<div class="dark-bg">
  <div class="container">
    <div class="d-flex home-container">
      <div class="left">
<!--       <div class="hero-section-responsive">
        <h3 id="hero-first-line">Whether you've just come back home from your travels</h3>
        <h3 id="hero-second-line">Or you're looking to go,</h3>
        <h3 id="hero-third-line">we've got you <b>covered</b></h3>
      </div> -->

        <div class="coin-headers">
          <div class="coin-1">
            <svg width="200" height="200" xmlns="http://www.w3.org/2000/svg" class="svg-coin-1" viewBox="0 0 200 200">
  <!--           <path d="M70 70 A 15 15 0 1 1 70 10" fill="none" stroke="gray" stroke-width="2" class="path"/>
            <path d="M70 10 A 15 15 0 1 1 70 70" fill="none" stroke="gray" stroke-width="2" class="path"/> -->
              <path
                d="
                  M 5, 35
                  a 30,30 0 1,1 60,0
                  a 30,30 0 1,1 -60,0
                "
              fill="none" stroke="gray" stroke-width="2" class="path-1"/>
            </svg>
            <div class="animated-coins" id="animated-coin-1" style="background-image: url(<%= image_path "gold-coin.png" %>);"></div>
          </div>
          <div class="coin-2">
            <svg width="200" height="200" xmlns="http://www.w3.org/2000/svg" class="svg-coin-2" viewBox="0 0 200 200">
              <path
                d="
                  M 5, 55
                  a 52,52 0 1,1 104,0
                  a 52,52 0 1,1 -104,0
                "
              fill="none" stroke="gray" stroke-width="2" class="path-2"/>
            </svg>
            <div class="animated-coins" id="animated-coin-2" style="background-image: url(<%= image_path "yen.png" %>);"></div>
          </div>
        </div>
        <h2 class="home-description">Exchange left over cash <br> for digital money,<br>wherever you are.</h2>
        <p class="revonew-description">Fast, secure transactions as recommended by billions of customers on Trustpilot, worldwide*</p>
        <div class="left-bottom">
          <%= link_to "Cash exchanges near you", listings_path, class: "blue-gradient-button-home" %>
          <%= link_to "New Exchange", new_listing_path, class: "exchange-button responsive" %>
          <div class="coin-3">
            <svg width="200" height="200" xmlns="http://www.w3.org/2000/svg" class="svg-coin-3" viewBox="0 0 200 200">
    <!--           <path d="M65 150 A 65 65 0 1 0 130 20" fill="none" stroke="gray" stroke-width="2" class="path"/>
              <path d="M130 20 A 65 65 0 1 0 65 150" fill="none" stroke="gray" stroke-width="2" class="path"/> -->
              <path
                d="
                  M 5, 75
                  a 73,73 0 1,1 146,0
                  a 73,73 0 1,1 -146,0
                "
              fill="none" stroke="gray" stroke-width="2" class="path-3"/>
            </svg>
            <div class="animated-coins" id="animated-coin-3" style="background-image: url(<%= image_path "royal-mint.png" %>);"></div>
          </div>
        </div>
      </div>

      <div class="right">
        <%= image_tag "hugo-resized.png", alt: "money", class: "home-img" %>
      </div>
    </div>
    <div class="disclaimer">
        <p>* this is purely a promotional statement and is in no way reflected by actual statistics</p>
    </div>
  </div>
    <div class="footnote-container">
      <div class="fluff w-40">
        <a href="#" class="footer-link"><p>About</p></a>
        <a href="#" class="footer-link"><p>Terms and Conditions</p></a>
        <a href="#" class="footer-link"><p>FAQ</p></a>
        <a href="http://www.github.com/stanleypliu/MaxMyCash" class="footer-link" id="responsive-repo"><p>GitHub</p></a>
      </div>
      <div class="acknowledgments w-60">
        <p>Made with 💟 by <b>HMDS</b> @ Le Wagon | batch #361 | Check out the GitHub repo here</p>
        <a href="http://www.github.com/stanleypliu/MaxMyCash" class="footer-link"><i class="fab fa-github"></i></a>
      </div>
    </div>
</div>

app/views/pages/payment.html.erb
<div class="container">
    <div class="card-box-shadow-review">
        <h3 style=" text-align: left"><b>Review order details:</b></h3>
        <h5 style=" text-align: left">Payment amount - <%= @listing.currency_amount %> </h5>
        <h5 style=" text-align: left">Currency - <%= @listing.currency %> </h5>
    </div>
  <div class="row justify-content-center">
    <div class="col-6">
      <h1 class="payment-heading" style="text-align: center;"><b>You're almost there!</b></h1>

    <div class="payment-card">
      <p class="pmt-instruction">Enter payment details below</p>
  <!--     <p><% @client_secret %></p>
   -->  <form id="payment-form">
        <div id="card-element">
          <!-- Elements will create input elements here -->
        </div>

        <!-- We'll put the error messages in this element -->
        <div id="card-errors" role="alert"></div>

        <button id="submit" class="btn btn-primary w-100 p-4px">Submit</button>
      </form>

      <script>

        var stripe = Stripe('pk_test_ta10eA8qEDhEo0uEOQzjrMm700J5gZYS9q');
        var elements = stripe.elements();

        var style = {
          base: {
            color: "#32325d",
          }
        };

        var card = elements.create("card", { style: style });
        card.mount("#card-element");

        card.addEventListener('change', ({error}) => {
          const displayError = document.getElementById('card-errors');
          if (error) {
            displayError.textContent = error.message;
          } else {
            displayError.textContent = '';
          }
        });
        var form = document.getElementById('payment-form');

        form.addEventListener('submit', function(ev) {
          ev.preventDefault();
          stripe.confirmCardPayment('<%= @client_secret %>', {
            payment_method: {
              card: card,
              billing_details: {
                name: 'Jenny Rosen'
              }
            }
          }).then(function(result) {
            if (result.error) {
              // Show error to your customer (e.g., insufficient funds)
              console.log(result.error.message);
            } else {
              // The payment has been processed!
              if (result.paymentIntent.status === 'succeeded') {
                // window.alert('Success')
                window.location.replace("<%= dashboard_path(paid: "paid") %>")


                // Show a success message to your customer
                // There's a risk of the customer closing the window before callback
                // execution. Set up a webhook or plugin to listen for the
                // payment_intent.succeeded event that handles any business critical
                // post-payment actions.
              }
            }
          });
        });
      </script>
    </div>
  <%= image_tag "money_transfer_.png", alt: "money", class: "payment-img" %>
  </div>
</div>

</div>